apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  volumes:
  - name: cache-volume
    emptyDir: {}
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo Hello > /cache/hello.txt && sleep 3600"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
