apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webstack
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 6379
    targetPort: 6379
