apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: "250m"     # 0.25 core requested (minimum guaranteed)
        memory: "128Mi" # 128 MB requested
      limits:
        cpu: "500m"     # max 0.5 core the container can use
        memory: "256Mi" # max 256 MB RAM
