apiVersion: v1
kind: Secret
metadata:
  name: my-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbDZmOG54di5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWTJoaGRIVnlkbVZrYVdwbWNtOW5RR2R0WVdsc0xtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUMFJuZVU1cWEzcE5SRWsyV2xWME1VMHlOVEphVkZGNlZsYzFhRlpxVWtaa00wSkhUVlpPTlU1VWFHeE5NakI0IgoJCX0KCX0KfQ== 
