apiVersion: v1
kind: Secret
metadata:
  name: my-regcred
  namespace: mini-project
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbDZmOG54di5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWTJoaGRIVnlkbVZrYVdwbWNtOW5RR2R0WVdsc0xtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUMFJqTWs1NlNUTk5WRmsyVjBaU2QxSkhhRXRXVkU0d1VtMUdZV0pGZEU1U1JXaFRUbFZqTVZGWWFIZFhSVll5IgoJCX0KCX0KfQo=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default   # ⚠️ careful, this overrides default SA in namespace
  namespace: mini-project
secrets:
- name: my-regcred
imagePullSecrets:
- name: my-regcred

