apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir
spec:
  containers:
    - name: app
      image: nginx:1.25
      volumeMounts:
        - name: cache-storage
          mountPath: /usr/share/nginx/html/cache
  volumes:
    - name: cache-storage
      emptyDir: {}
