apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-env
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo USER=$DB_USER && echo PASS=$DB_PASS && sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
