apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-sa
  namespace: default
imagePullSecrets:
- name: my-registry-secret


---

apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  namespace: default
spec:
  serviceAccountName: my-app-sa
  containers:
  - name: mycontainer
    image: <REGISTRY_URL>/<NAMESPACE>/<IMAGE>:<TAG>
