apiVersion: v1
kind: Pod
metadata:
  name: nginx-redis-pod
  labels:
    app: webstack
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
  - name: redis
    image: redis:7
    ports:
    - containerPort: 6379
