apiVersion: v1
kind: Pod
metadata:
  name: single-container
  labels:
    app: single-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: single-nginx-svc
spec:
  selector:
    app: single-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP

