apiVersion: v1
kind: Pod
metadata:
  name: pod-user-1000
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  containers:
  - name: custom-user
    image: alpine:3.19
    command: ["sh", "-c", "id; sleep 3600"]
